name: myapp
description: Proyecto Flutter inicial

version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.4.0
  flutter_riverpod: ^2.6.1
  go_router: ^13.0.0
  http: ^0.13.6
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/static/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/static/Inter_18pt-Regular.ttf
        - asset: assets/fonts/static/Inter_18pt-Medium.ttf
          weight: 500
        - asset: assets/fonts/static/Inter_18pt-Bold.ttf
          weight: 700
