name: myapp
description: Proyecto Flutter inicial

version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_reactive_ble: ^5.4.0
  flutter_riverpod: ^2.6.1
  go_router: ^13.0.0
  http: ^0.13.6
  permission_handler: ^12.0.0+1
